### ISSUE TITLE
Change in the behavior of get_window_alpha in scheduler_perflow.py

### ISSUE THREAD

**Issue by feifeiobama** [magic-research/piecewise-rectified-flow#7]
Hi there,

First, congratulations on releasing such an easy-to-use codebase!

I recently upgraded the codebase from 9bfc04 to the latest version, but encountered a change in the behavior of get_window_alpha:
* In the previous version, when using SD 1.5 with prediction_type="epsilon", we have:
  * `get_window_alpha(torch.tensor(250))[4] = 0.8222`
  * `get_window_alpha(torch.tensor(500))[4] = 0.6412`
  * `get_window_alpha(torch.tensor(750))[4] = 0.4516`
  * `get_window_alpha(torch.tensor(1000))[4] = 0.2869`
* In the latest version, when using SD 1.5 with prediction_type="diff_eps", they all return `0.2869`.

I am wondering which is the right one for SD 1.5 with epsilon prediction.

**Comment by HanshuYAN** [comment]
Hi,
Thanks for your interest in our work. This issue comes from here: https://github.com/magic-research/piecewise-rectified-flow/blob/c530cf76e54587ab85f0c6d00b9bca54d055da03/src/scheduler_perflow.py#L312

In the previous version, we did not rescale the timestep into the range of [0,1] before passing to get_window_alpha.

**Comment by feifeiobama** [comment]
Got it, thanks!
